name: ContextualNotes
options:
  bundleIdPrefix: com.omnia
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  ContextualNotes:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ContextualNotes
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.omnia.ContextualNotes
        DEVELOPMENT_TEAM: 279PV9XKZ2
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: ContextualNotes/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
